CREATE TABLE IF NOT EXISTS players
(
    uuid CHAR(36) NOT NULL,
	name VARCHAR(16),
	email VARCHAR(80),
	pwhash CHAR(128),
	salt CHAR(64),
    chat BOOLEAN NOT NULL DEFAULT TRUE,
    pms INTEGER NOT NULL DEFAULT 1,
    suffix VARCHAR(16) NOT NULL DEFAULT "",
    lang CHAR(2) NOT NULL DEFAULT "en",
    tabcompletion BOOLEAN NOT NULL DEFAULT FALSE,
    scoreboard BOOLEAN NOT NULL DEFAULT TRUE,
	friendReqs BOOLEAN NOT NULL DEFAULT TRUE,
	sendPackPrompt BOOLEAN NOT NULL DEFAULT TRUE,
	tipFirstFriend BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (uuid)
);
·
CREATE INDEX IF NOT EXISTS idx_name ON players(name);
·
CREATE TABLE IF NOT EXISTS friends
(
	player1 CHAR(36) NOT NULL,
	player2 CHAR(36) NOT NULL,
	PRIMARY KEY (player1, player2),
	FOREIGN KEY (player1) REFERENCES players(uuid) ON DELETE CASCADE,
	FOREIGN KEY (player2) REFERENCES players(uuid) ON DELETE CASCADE
);
·
CREATE INDEX IF NOT EXISTS idx_player1 ON friends (player1);
CREATE INDEX IF NOT EXISTS idx_player2 ON friends (player2);
·
CREATE TABLE IF NOT EXISTS ignores
(
	ignored CHAR(36) NOT NULL,
	issuer CHAR(36) NOT NULL,
	PRIMARY KEY (issuer, ignored),
	FOREIGN KEY (issuer) REFERENCES players(uuid) ON DELETE CASCADE,
	FOREIGN KEY (ignored) REFERENCES players(uuid) ON DELETE CASCADE
);
·
CREATE TABLE IF NOT EXISTS punishments
(
	id INTEGER PRIMARY KEY NOT NULL,
	reason VARCHAR(255) NOT NULL DEFAULT "Unspecified",
	creationDate DATETIME NOT NULL,
	expirationDate DATETIME,
	type INTEGER NOT NULL,
	player CHAR(36) NOT NULL,
	FOREIGN KEY (player) REFERENCES players(uuid) ON DELETE CASCADE
);
·
CREATE TABLE IF NOT EXISTS notes
(
	id INTEGER PRIMARY KEY NOT NULL,
	note VARCHAR(255) NOT NULL,
	player CHAR(36) NOT NULL,
	FOREIGN KEY (player) REFERENCES players(uuid) ON DELETE CASCADE
);
·
CREATE TABLE IF NOT EXISTS inboxes
(
	id INTEGER NOT NULL,
	submissionDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	player CHAR(36) NOT NULL,
	FOREIGN KEY (player) REFERENCES players(uuid) ON DELETE CASCADE
);
·
CREATE TABLE IF NOT EXISTS inbox_global_messages
(
    id INTEGER NOT NULL,
	issuer TEXT NOT NULL,
	title TEXT NOT NULL,
	msg TEXT NOT NULL,
	action TEXT NOT NULL,
	creationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);
·
CREATE TABLE IF NOT EXISTS in_data_reward_coins
(
	id INTEGER PRIMARY KEY NOT NULL,
	coins INTEGER NOT NULL,
	FOREIGN KEY (id) REFERENCES inboxes(id) ON DELETE CASCADE
);
·
CREATE TABLE IF NOT EXISTS in_data_prac_keffect
(
	id INTEGER PRIMARY KEY NOT NULL,
	ordinal INTEGER NOT NULL,
	FOREIGN KEY (id) REFERENCES inboxes(id) ON DELETE CASCADE
);
·
CREATE TABLE IF NOT EXISTS in_data_compensate_elo
(
	id INTEGER PRIMARY KEY NOT NULL,
	elo INTEGER NOT NULL,
	FOREIGN KEY (id) REFERENCES inboxes(id) ON DELETE CASCADE
);
